easy_admin:
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            edit:
                fields:
                - { property: 'plainPassword', type: 'text', type_options: { required: false, empty_data: '' }, 'label': 'New password' }
                - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            new:
                fields:
                - { property: 'email', type_options: { required: true, }, 'label': 'Email' }
                - { property: 'plainPassword', type: 'text', type_options: { required: true, empty_data: '' }, 'label': 'Password' }
                - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
        Post:
            class: App\Entity\Post
            edit:
                fields:
                - { property: 'title' }
                - { property: 'content', type: 'textarea' }
                - { property: 'author'  }
            new:
                fields:
                - { property: 'title' }
                - { property: 'content', type: 'textarea' }
                - { property: 'author'  }
            list:
               fields: [ 'id', 'title', 'created', 'updated', { property: 'authorEmail', label: 'Author' }, { property: 'comments', label: 'Comments Count'} ]
        Comment:
            class: App\Entity\Comment
            edit:
                fields:
                - { property: 'content', type: 'textarea' }
                - { property: 'post'  }
                - { property: 'author'  }
            new:
                fields:
                - { property: 'content', type: 'textarea' }
                - { property: 'post'  }
                - { property: 'author'  }
            list:
                fields: [ 'id', 'content', 'created', 'updated', { property: 'post', label: 'Post ID' }, { property: 'authorEmail', label: 'Author' } ]